# Generated by Django 3.1.6 on 2021-02-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0006_auto_20210219_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertelegram',
            name='id_user',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
