# Generated by Django 3.1.6 on 2021-02-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0008_auto_20210227_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='id_user_telegram',
            field=models.IntegerField(null=True),
        ),
    ]
