# Generated by Django 3.1.6 on 2021-03-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0009_auto_20210227_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertelegram',
            name='id',
        ),
        migrations.AlterField(
            model_name='usertelegram',
            name='id_user_telegram',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
