# Generated by Django 3.1.6 on 2021-02-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appserver', '0004_auto_20210210_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MessageInfo',
            fields=[
                ('after_question', models.BooleanField()),
                ('id_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appadmin.question')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceMessageQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appadmin.message')),
                ('question', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appadmin.question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswersUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=150)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appadmin.question')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appserver.usertelegram')),
            ],
        ),
    ]
