# Generated by Django 3.1.6 on 2021-02-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0002_auto_20210211_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SequenceMessageQuestion',
            new_name='Message_Question',
        ),
    ]
