# Generated by Django 3.1.6 on 2021-02-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0005_auto_20210212_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message_Question',
            new_name='Sequence_Logic',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_confirm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_not_confirm',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
