# Generated by Django 3.1.6 on 2021-02-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0007_message_logic_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='logic_order',
            field=models.IntegerField(null=True),
        ),
    ]
