# Generated by Django 3.1.6 on 2021-02-17 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0010_auto_20210217_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_sequence_logic',
            name='number_record_logic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appadmin.sequence_logic'),
        ),
    ]
