# Generated by Django 3.1.6 on 2021-02-18 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0004_auto_20210210_0514'),
        ('appadmin', '0011_auto_20210217_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appadmin.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appserver.usertelegram')),
            ],
        ),
    ]
