# Generated by Django 3.1.6 on 2021-02-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0012_answeruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='logic_order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_confirm',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_not_confirm',
        ),
    ]
