# Generated by Django 3.1.6 on 2021-02-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0013_auto_20210226_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers_For_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answert_text', models.CharField(max_length=150)),
                ('type_next_entity', models.CharField(max_length=150)),
                ('id_next_message', models.IntegerField(null=True)),
                ('id_next_question', models.IntegerField(null=True)),
            ],
        ),
    ]
