# Generated by Django 3.1.6 on 2021-02-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0014_answers_for_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='logic_order',
            new_name='id_parent',
        ),
        migrations.AddField(
            model_name='message',
            name='display_condition',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
