# Generated by Django 3.1.6 on 2021-02-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0015_auto_20210226_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers_For_Questions',
        ),
        migrations.RemoveField(
            model_name='answeruser',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answeruser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sequence_logic',
            name='message',
        ),
        migrations.RemoveField(
            model_name='sequence_logic',
            name='question',
        ),
        migrations.RemoveField(
            model_name='user_sequence_logic',
            name='number_record_logic',
        ),
        migrations.RemoveField(
            model_name='user_sequence_logic',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='write_answer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answers_Users',
        ),
        migrations.DeleteModel(
            name='AnswerUser',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Sequence_Logic',
        ),
        migrations.DeleteModel(
            name='User_Sequence_Logic',
        ),
    ]
