# Generated by Django 3.1.6 on 2021-02-27 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0016_auto_20210227_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='write_answer',
            new_name='answer_write',
        ),
    ]
