# Generated by Django 3.1.6 on 2021-02-27 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0017_auto_20210227_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='answer_write',
            new_name='write_answer',
        ),
    ]
