# Generated by Django 3.1.6 on 2021-02-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0018_auto_20210227_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='display_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='write_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
