# Generated by Django 3.1.6 on 2021-02-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0021_auto_20210227_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='write_answer',
            field=models.CharField(choices=[('Пользователь отвечает на сообщение', 'Пользователь не отвечает на сообщение')], max_length=100),
        ),
    ]
