# Generated by Django 3.1.6 on 2021-02-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0022_auto_20210227_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='write_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
