# Generated by Django 3.1.6 on 2021-03-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0023_auto_20210227_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_bot', models.CharField(max_length=500)),
            ],
        ),
    ]
