# Generated by Django 3.1.6 on 2021-03-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0025_messagedelay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagedelay',
            old_name='message_id',
            new_name='message',
        ),
    ]
