# Generated by Django 3.1.6 on 2021-03-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0026_auto_20210301_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagedelay',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appadmin.message'),
        ),
    ]
