# Generated by Django 3.1.6 on 2021-03-02 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appserver', '0010_auto_20210302_0937'),
        ('appadmin', '0027_auto_20210301_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appserver.usertelegram')),
            ],
        ),
    ]
