# Generated by Django 3.1.6 on 2021-03-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0028_answeruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeruser',
            old_name='id_telegram_user',
            new_name='telegram_user',
        ),
        migrations.AddField(
            model_name='answeruser',
            name='message',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appadmin.messagedelay'),
            preserve_default=False,
        ),
    ]
