# Generated by Django 3.1.6 on 2021-03-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0029_auto_20210302_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeruser',
            name='answer',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
