# Generated by Django 3.1.6 on 2021-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0031_auto_20210302_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text_message',
            field=models.CharField(max_length=500),
        ),
    ]
