# Generated by Django 3.1.6 on 2021-03-07 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0032_auto_20210304_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('first_name', models.CharField(default=None, max_length=30, null=True)),
                ('last_name', models.CharField(default=None, max_length=30, null=True)),
                ('username', models.CharField(default=None, max_length=30, null=True)),
                ('id_user_telegram', models.IntegerField(primary_key=True, serialize=False)),
                ('id_current_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appadmin.message')),
            ],
        ),
        migrations.AlterField(
            model_name='answeruser',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appadmin.usertelegram'),
        ),
    ]
