# Generated by Django 3.1.6 on 2021-03-07 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0033_auto_20210307_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertelegram',
            name='id_current_message',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appadmin.message'),
        ),
    ]
