# Generated by Django 3.1.6 on 2021-03-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0034_auto_20210307_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertelegram',
            old_name='id_current_message',
            new_name='current_message',
        ),
    ]
